build:
  cargo build

install-ios-targets:
    @echo "==> Installing iOS targets..."
    rustup target add aarch64-apple-ios-sim
    rustup target add aarch64-apple-ios
    @echo "iOS targets installed"

build-ios:
    @echo "==> Building iOS..."